version: 2.1
orbs:
    sonarcloud: sonarsource/sonarcloud@1.0.2
commands:
    node-install:
        steps:
            - run: npm ci
    node-linter:
        steps:
            - run: npm run lint -- --format html --output-file ./coverage/lint/index.html
            - store_artifacts:
                path: ./coverage
    node-test:
        steps:
            - run:
                when: always
                command: npm run test -- --reporter mocha-multi-reporters --reporter-options configFile=./test/reporter-config.json
                environment:
                    MOCHAWESOME_REPORTFILENAME: index.html
                    MOCHAWESOME_REPORTDIR: ./coverage/unit-test
            - store_test_results:
                path: ./coverage/reports
            - store_artifacts:
                path: ./coverage
    node-report:
        steps:
            - run: npm run report
            - store_artifacts:
                path: ./coverage
    npm-deploy:
        steps:
            - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
            - run: npm version $CIRCLE_TAG --allow-same-version --no-git-tag-version
            - run: npm publish --access public
jobs:
    install-build-test:
        docker:
            - image: node:14
        steps:
            - checkout
            - node-install
            - node-linter
            - node-test
            - node-report
            - sonarcloud/scan
    install-build-deploy:
        docker:
            - image: node:14
        steps:
            - checkout
            - node-install
            - npm-deploy
workflows:
    install-build-deploy:
        jobs:
            - install-build-deploy:
                context:
                    - shared-sonarcloud-token
                    - shared-npm-org-token
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
    install-build-test:
        jobs:
            - install-build-test:
                context:
                    - shared-sonarcloud-token
                    - shared-npm-org-token
                filters:
                    tags:
                        ignore: /.*/
                    branches:
                        ignore: /dependabot.*/
